FROM python:3.8.13

# TODO - add all the necessary to run the script populate_db.py in this image
# 1. Copy the requirements.txt file to the image
# 2. Install the dependencies
# 3. Copy the content of the current directory to the image
# 4. Run the populate_db.py script

WORKDIR /src

# Install dependences
COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

# Copy app code
COPY . .

# Run app
CMD python3 populate_db.py



